name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train NLP model
      run: |
        python train_nlp.py

    - name: Train Vision model
      run: |
        python train_vision.py

    - name: Build Docker image
      run: |
        docker build -t my_model_server .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag my_model_server ${{ secrets.DOCKER_USERNAME }}/my_model_server:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my_model_server:latest

    - name: Deploy to Kubernetes
      uses: manusa/actions-setup-kubectl@v2
      with:
        version: 'v1.18.0'

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
